[package]
name = "craftec-settlement"
version = "0.1.0"
description = "Craftec settlement program — shared by all crafts"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "craftec_settlement"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
anchor-spl = { version = "0.31.1", features = ["token", "associated_token"] }
sha2 = "0.10"
